const A4 = {
  landscape: { width: 1123, height: 794 },
  portrait: { width: 794, height: 1123 },
};

const roles = {
  "Super Admin": ["*"],
  Admin: ["template:create", "template:edit", "student:edit", "import", "generate", "approve", "revoke", "audit:view", "number:override"],
  "Academic Officer": ["student:edit", "approve", "audit:view"],
  "Finance Officer": ["finance:clear", "audit:view"],
  "Certificate Officer": ["template:edit", "generate", "download", "audit:view"],
  "Data Entry User": ["student:edit", "import"],
  Verifier: ["verify", "audit:view"],
  Viewer: ["audit:view"],
};

const fieldCatalog = [
  "student_name", "printed_name", "registration_number", "certificate_ref", "award_body", "campus_name",
  "programme_name", "course_name", "qualification_title", "award_title", "specialisation", "grade",
  "classification", "gpa", "credits", "academic_year", "start_date", "end_date", "award_date",
  "issue_date", "completion_date", "authorised_signatory", "dean_name", "director_name",
  "qr_verification_link", "custom_notes"
];

const fontOptions = [
  { name: "Arial", value: "Arial, Helvetica, sans-serif", group: "Universal" },
  { name: "Helvetica", value: "Helvetica, Arial, sans-serif", group: "Universal" },
  { name: "Times New Roman", value: "'Times New Roman', Times, serif", group: "Serif" },
  { name: "Georgia", value: "Georgia, 'Times New Roman', serif", group: "Serif" },
  { name: "Garamond", value: "Garamond, Georgia, serif", group: "Serif" },
  { name: "Palatino", value: "Palatino, 'Palatino Linotype', serif", group: "Serif" },
  { name: "Verdana", value: "Verdana, Geneva, sans-serif", group: "Sans-serif" },
  { name: "Tahoma", value: "Tahoma, Geneva, sans-serif", group: "Sans-serif" },
  { name: "Trebuchet MS", value: "'Trebuchet MS', Arial, sans-serif", group: "Sans-serif" },
  { name: "Courier New", value: "'Courier New', Courier, monospace", group: "Monospace" },
  { name: "Brush Script", value: "'Brush Script MT', cursive", group: "Cursive" },
  { name: "Zapfino", value: "Zapfino, 'Brush Script MT', cursive", group: "Cursive" },
  { name: "Sinhala Unicode", value: "'Iskoola Pota', 'Noto Sans Sinhala', 'Malithi Web', sans-serif", group: "Sinhala" },
  { name: "Tamil Unicode", value: "'Noto Sans Tamil', 'Latha', 'Tamil Sangam MN', sans-serif", group: "Tamil" },
  { name: "Noto Sans Universal", value: "'Noto Sans', 'Noto Sans Sinhala', 'Noto Sans Tamil', Arial, sans-serif", group: "Unicode" },
  { name: "Noto Serif Universal", value: "'Noto Serif', 'Noto Serif Sinhala', 'Noto Serif Tamil', Georgia, serif", group: "Unicode" },
  { name: "Apple System", value: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", group: "System" },
  { name: "Academic Serif", value: "Georgia, 'Times New Roman', 'Noto Serif', serif", group: "Certificate" },
  { name: "Formal Sans", value: "'Segoe UI', Arial, 'Noto Sans', sans-serif", group: "Certificate" }
];

const sampleStudents = [
  {
    id: "STU-1001",
    student_name: "Amaya Perera",
    printed_name: "AMAYA PERERA",
    registration_number: "PIC/BBA/2026/001",
    nic: "200112345678",
    email: "amaya@example.edu",
    phone: "+94 77 123 4567",
    campus_name: "Colombo Campus",
    programme_name: "Bachelor of Business Administration",
    award_body: "Pioneer International College",
    batch: "BBA 2024",
    intake: "January",
    status: "completed",
    qualification_title: "BACHELOR OF BUSINESS ADMINISTRATION",
    award_title: "Degree",
    specialisation: "Business Management",
    grade: "A",
    classification: "Merit",
    gpa: "3.62",
    credits: "120",
    academic_year: "2025/2026",
    award_date: "2026-05-19",
    issue_date: "2026-05-19",
    completion_date: "2026-04-30",
    authorised_signatory: "Dr. N. Wijesinghe",
    dean_name: "Prof. Helena Morris",
    director_name: "Mr. D. Fernando",
    custom_notes: "Awarded after successful completion of all academic and administrative requirements."
  },
  {
    id: "STU-1002",
    student_name: "தர்ஷன் குமார்",
    printed_name: "தர்ஷன் குமார்",
    registration_number: "PIC/MBA/2026/014",
    nic: "P1234567",
    email: "darshan@example.edu",
    phone: "+94 76 222 8800",
    campus_name: "Kandy Campus",
    programme_name: "Master of Business Administration",
    award_body: "Global Awarding Council",
    batch: "MBA 2025",
    intake: "September",
    status: "completed",
    qualification_title: "MASTER OF BUSINESS ADMINISTRATION",
    award_title: "Master's Degree",
    specialisation: "Strategic Management",
    grade: "A-",
    classification: "Distinction",
    gpa: "3.81",
    credits: "90",
    academic_year: "2025/2026",
    award_date: "2026-05-19",
